//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyatyPointSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string ID_No { get; set; }
        public string Email { get; set; }
        public string Cell_No { get; set; }
        public Nullable<decimal> Loyalty_Points { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
